// IPC channel names shared between main and preload.

export const CH = {
  reposList: 'repos:list',
  repoAdd: 'repos:add',
  repoRemove: 'repos:remove',
  groupsList: 'groups:list',
  groupCreate: 'groups:create',
  groupRename: 'groups:rename',
  groupDelete: 'groups:delete',
  groupAssign: 'groups:assign',
  groupSetFeatureId: 'groups:setFeatureId',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  openFolder: 'dialog:openFolder',
  revealInFileManager: 'shell:reveal',
  openInTerminal: 'shell:terminal',

  status: 'git:status',
  log: 'git:log',
  branches: 'git:branches',
  stashes: 'git:stashes',
  remotes: 'git:remotes',
  tags: 'git:tags',
  submodules: 'git:submodules',
  diffWorking: 'git:diffWorking',
  commitFiles: 'git:commitFiles',
  commitFileDiff: 'git:commitFileDiff',
  compareFiles: 'git:compareFiles',
  compareFileDiff: 'git:compareFileDiff',
  stashFiles: 'git:stashFiles',
  stashFileDiff: 'git:stashFileDiff',

  stage: 'git:stage',
  unstage: 'git:unstage',
  stageAll: 'git:stageAll',
  unstageAll: 'git:unstageAll',
  discard: 'git:discard',
  commit: 'git:commit',
  checkout: 'git:checkout',
  createBranch: 'git:createBranch',
  renameBranch: 'git:renameBranch',
  merge: 'git:merge',
  deleteBranch: 'git:deleteBranch',
  push: 'git:push',
  pull: 'git:pull',
  fetch: 'git:fetch',
  stashSave: 'git:stashSave',
  stashApply: 'git:stashApply',
  stashDrop: 'git:stashDrop',
  addRemote: 'git:addRemote',
  removeRemote: 'git:removeRemote',
  createTag: 'git:createTag',
  deleteTag: 'git:deleteTag',
  pushTag: 'git:pushTag',
  submoduleUpdate: 'git:submoduleUpdate',
  rebase: 'git:rebase',
  revertCommit: 'git:revertCommit',
  resetTo: 'git:resetTo',
  cherryPick: 'git:cherryPick',
  restoreFileFromCommit: 'git:restoreFileFromCommit',
  externalDiffCommit: 'git:externalDiffCommit',
  copyText: 'clipboard:writeText',
  applyPatch: 'git:applyPatch',
  appRefresh: 'app:refresh'
} as const

export type ChannelName = (typeof CH)[keyof typeof CH]
